syntax = "proto3";

package tarefa;

service TarefaService {
    rpc CreateTarefa (CreateTarefaRequest) returns (TarefaResponse);
    rpc ListTarefas (Empty) returns (ListTarefasResponse);
    rpc UpdateTarefa (UpdateTarefaRequest) returns (TarefaResponse);
    rpc DeleteTarefa (TarefaRequest) returns (DeleteTarefaResponse);
}

message Empty {}

message Tarefa {
    string id = 1;
    string title = 2;
    bool completed = 3;

}

message CreateTarefaRequest {
    string title = 1;
}

message TarefaRequest {
    string id = 1;
}

message TarefaResponse {
    Tarefa tarefa = 1;
}

message ListTarefasResponse {
    repeated Tarefa tarefas = 1;
}

message UpdateTarefaRequest {
    string id = 1;
    string title = 2;
    bool completed = 3;
}

message DeleteTarefaResponse {
    bool success = 1;
}
