# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tarefa_pb2 as tarefa__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tarefa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TarefaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTarefa = channel.unary_unary(
                '/tarefa.TarefaService/CreateTarefa',
                request_serializer=tarefa__pb2.CreateTarefaRequest.SerializeToString,
                response_deserializer=tarefa__pb2.TarefaResponse.FromString,
                _registered_method=True)
        self.ListTarefas = channel.unary_unary(
                '/tarefa.TarefaService/ListTarefas',
                request_serializer=tarefa__pb2.Empty.SerializeToString,
                response_deserializer=tarefa__pb2.ListTarefasResponse.FromString,
                _registered_method=True)
        self.UpdateTarefa = channel.unary_unary(
                '/tarefa.TarefaService/UpdateTarefa',
                request_serializer=tarefa__pb2.UpdateTarefaRequest.SerializeToString,
                response_deserializer=tarefa__pb2.TarefaResponse.FromString,
                _registered_method=True)
        self.DeleteTarefa = channel.unary_unary(
                '/tarefa.TarefaService/DeleteTarefa',
                request_serializer=tarefa__pb2.TarefaRequest.SerializeToString,
                response_deserializer=tarefa__pb2.DeleteTarefaResponse.FromString,
                _registered_method=True)


class TarefaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTarefas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TarefaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTarefa,
                    request_deserializer=tarefa__pb2.CreateTarefaRequest.FromString,
                    response_serializer=tarefa__pb2.TarefaResponse.SerializeToString,
            ),
            'ListTarefas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTarefas,
                    request_deserializer=tarefa__pb2.Empty.FromString,
                    response_serializer=tarefa__pb2.ListTarefasResponse.SerializeToString,
            ),
            'UpdateTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTarefa,
                    request_deserializer=tarefa__pb2.UpdateTarefaRequest.FromString,
                    response_serializer=tarefa__pb2.TarefaResponse.SerializeToString,
            ),
            'DeleteTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTarefa,
                    request_deserializer=tarefa__pb2.TarefaRequest.FromString,
                    response_serializer=tarefa__pb2.DeleteTarefaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarefa.TarefaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarefa.TarefaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TarefaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/CreateTarefa',
            tarefa__pb2.CreateTarefaRequest.SerializeToString,
            tarefa__pb2.TarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTarefas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/ListTarefas',
            tarefa__pb2.Empty.SerializeToString,
            tarefa__pb2.ListTarefasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/UpdateTarefa',
            tarefa__pb2.UpdateTarefaRequest.SerializeToString,
            tarefa__pb2.TarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefa.TarefaService/DeleteTarefa',
            tarefa__pb2.TarefaRequest.SerializeToString,
            tarefa__pb2.DeleteTarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
