# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\x12\x06tarefa\"\x07\n\x05\x45mpty\"6\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"$\n\x13\x43reateTarefaRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1b\n\rTarefaRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x0eTarefaResponse\x12\x1e\n\x06tarefa\x18\x01 \x01(\x0b\x32\x0e.tarefa.Tarefa\"6\n\x13ListTarefasResponse\x12\x1f\n\x07tarefas\x18\x01 \x03(\x0b\x32\x0e.tarefa.Tarefa2\x8f\x01\n\rTarefaService\x12\x43\n\x0c\x43reateTarefa\x12\x1b.tarefa.CreateTarefaRequest\x1a\x16.tarefa.TarefaResponse\x12\x39\n\x0bListTarefas\x12\r.tarefa.Empty\x1a\x1b.tarefa.ListTarefasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_TAREFA']._serialized_start=33
  _globals['_TAREFA']._serialized_end=87
  _globals['_CREATETAREFAREQUEST']._serialized_start=89
  _globals['_CREATETAREFAREQUEST']._serialized_end=125
  _globals['_TAREFAREQUEST']._serialized_start=127
  _globals['_TAREFAREQUEST']._serialized_end=154
  _globals['_TAREFARESPONSE']._serialized_start=156
  _globals['_TAREFARESPONSE']._serialized_end=204
  _globals['_LISTTAREFASRESPONSE']._serialized_start=206
  _globals['_LISTTAREFASRESPONSE']._serialized_end=260
  _globals['_TAREFASERVICE']._serialized_start=263
  _globals['_TAREFASERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
